name: CI

on:
  pull_request:
  push:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: npm ci
      - run: npm run build
